//  Global info
export const GLOBAL_INFO_LOADING = 'GLOBAL_INFO_LOADING';
export const GLOBAL_INFO_LOAD_SUCCESS = 'GLOBAL_INFO_LOAD_SUCCESS';
export const GLOBAL_INFO_LOAD_FAIL = 'GLOBAL_INFO_LOAD_FAIL';
//  Testimonial
export const TESTIMONIAL_INFO_LOADING = 'TESTIMONIAL_INFO_LOADING';
export const TESTIMONIAL_INFO_LOAD_SUCCESS = 'TESTIMONIAL_INFO_LOAD_SUCCESS';
export const TESTIMONIAL_INFO_LOAD_FAIL= 'TESTIMONIAL_INFO_LOAD_FAIL';
//  Configurator
export const CONFIGURATOR_INFO_LOADING = 'CONFIGURATOR_INFO_LOADING';
export const CONFIGURATOR_INFO_LOAD_SUCCESS = 'CONFIGURATOR_INFO_LOAD_SUCCESS';
export const CONFIGURATOR_INFO_LOAD_FAIL = 'CONFIGURATOR_INFO_LOAD_FAIL';
